apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeCluster
metadata:
  name: a-team
  labels:
    cluster-owner: vfarcic
spec:
  id: a-team
  compositionRef:
    name: cluster-aws
  parameters:
    # Possible values small, medium, large
    nodeSize: small
    # version: "1.20"
    minNodeCount: 3
