apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBgRt3W19XSLQwFPz6UWP6UF0hjBHF1a1YIAkub/5hSdHoKHEOeRcRbeeZXPYGGedf8Ln9Ll+HbWzpL/ZeVzfEnKY9bCb7gWzz2jUC8eiyFHHaskUXjRsBlq2ZD0br0FXlpRixV7qBM3aNXqJx5cjNn6Ea/YZYUKU96UaBPkliqjiI4pobM+c5V9PPLl0JiYQNJtzJNyZ2YtrOEwrwLejpvF0p/N8I8/EokqROpOWOiXCN1cs1F2LlAB5bvKg668L92HQlWJ6T+Gu9YYRoZiLI3qwptZZoMTGBQGq5TYYjIorRpEGcaR5ugLDDgDfpxq7hsyJ3Q8QpYaoWKmXMisMzAgUuzRRdupKHIYHsH6Ge8KZAiF9SyXoWFABgVvMF3Ys/CMJuBTJfJlqUonLDzsoRi1QtY61RWWwnhs3trpAn0dwsLxdjakKeM98WIHYGiBSWaH1AEc2FDZvihTGzC2KSFaPu1rILllwrygI2odf0LSBOhZt1dFEGFRNCsrN8KWd2tn1/KWKmVDs41OcM3XHliAEcxHQVXEfNwZVal5nHCPgX6sZRaPZ9kfvW22EFdqc9YmKAAX29bihEssnbSSnXQj9QEQL2tPPt2EJuWy9iakffPDbVXcB5g6mHjanx7azAOQjZU/CGYOF4/nE49jKyYTaw3SU5gAelxoaFp6OU+cwPQ5q758MTAQzpEvZp363wg0nmJwYGNBO7JB/6/RNvb06Ube0HuIqhAj0lxVESLg3TN6Vq7LlHTsfre6lQvVYc8YrFstL62F52jPdRjEbjan9KADOvqsUnFbgZLv9i9JXXEHPEKbAWvDEXANtB+ytDkrythbVanlxoMyVvB6PfkbqQlrd4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

