apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA2UATQ0ltzcOW0RFDgIOgzBF2LLrJ5LwHRLRLO9WL+TywSQSJXcHq8p7gYjtji0EPUQrgveT+uHz4z+tB0/Yaa8bgk+n8vpUtBrfwdUYSOJA4FnOaFfDnP9TYYoerMEEEms1jBRHJsuDup5HTaRpdLiKOL57077gym1olehWdncMLBgFHpFlpYxbdnKmIdR4DPfQ0gPKNQV5P8nUhfBJsAAPwViMEOVfGcL1LoGrGWWF4uceIVtMcspEALQnpOB/UPnfv12xAJKj5XkvlzONlYmIdBt+8y3xy+0harfyHl6X3nzuFzecyBG4LKTFGWsT9myIpBlYcL7VuifAKNNn0V9oLgxZsTb6XVqiWMK2kg16pU2sYza0eHj5z5n1XNG7HgxmGytxkSsx6up3/hhqVdpgwiJjvZLJoQlhoQHS8CDu/lWF7/Nbz3Net3mveF1VStF3qswJwzDjDh1ad2wll1s4NwiexA0PotntlGWc/O2kyDnoFvnl96ASPgJdWnuZC8zHUWgRNSL/fJJzQy9WbRKbVCgDi6Oq8D22XdMyRIsjNi005ioSlSPqH9ta1nTcMUHERSQiToFrDRa5dlZBOQITFDP+0S4Ym9GLr4CWEg+kGauq/ET4PElpTi0tciToXvovLPkDg08c1hN5Lu0yLLkOpjFetNXvQwwWy4RdduCuZmkhVuY3ospiaM3FdfB3+PpL5qTe9j0mAxXFIXczhCxRrKvw5vbqpHtFAZzYpX7g/7S+fOnB0S2at1PL1ibazQuQLJshheEnPduquE+3YV1mi/lAAQYrPJqL74dvDdBbJS6DJix87BrUdAwuCC5upbrsm/t3mXum+CiWyQPgcTY7ui9L4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

