apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgDXD5cDrAA2mf8Q/nErbp9aBE9MhNSwJRZkYr4cFQGZga50Iub6KM7N4Jxg7sCviDP9DqoN3/A1ChjCI5TmMWDehqj7nJ1frfNSG0TBcRFrr+nSYe24F9YTI/+qepCzqctu16jJMqd/zcbeA/Pwo7/Cf8JjTNQmoVu1UFOEnenhnnI5A5Nk/pGSTcyAw0SMjLK2S9d3HGdzXrdODrX+xIqkBVpDjyuja0EtfsEaCn94U9X9o648JSh0txP4Fdis0ASE8v7cKtRaN9kNCrZpaiklfSJP+yb4+hmPXyLu9uvJ2Zx6pltWDr/drsBdx7FhRB6azuosuvwzpvakw1spP3x/rMM14YlIObWTQQhIQuAFX1uvCpJ3isnzS9eY/Hra2FjW9jTkphyeMhSw12/hAveZYoa5LrSHnuP2U/RXvEsG/6jJsbh5fChzvUH81Egrf3TIzwuEuFMZafpMxUywVm7mbS/xB8BoB3xxG+xOsrun3XK/uYI6q8L5XfL01Emvese1i6yjX5E6xE9zeZG4fwmCe3GVLQy7DL15HxN4Ehq2z3ZbP5wVgGwH/3/irvc0EFq61JjU5a8zMlVkjT6Mk14Nzl3FVKx+7gHCP/V2CuxhFNX8r5OPjIqp566Znw+SN19LurXwBBVSAdFoXZaEtpU601kBLhCZEETDy68zTcJU9IlKytdiIaSZiUYd6wU2gOiR3hFHpM3wn+oncSSxxd88NVMyMXZDgEvw1K/FbuIDlI2QqZ5wqFdgEBa+YSmy8t0yxtgG0RFKUXOF3e7KYItD+XDd33I+2WDrZkdmg/OQ5YOlPe7AMwLidpIp/SowGznmCKuF4nIZn4aWPgUJN0fXnEyF420=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

