apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCj9C7y8/sGFwyWDMZ+x0OADTD2SBBcDevHXOIMrmXeNERKujBBZQVcMOsfxEUq7/v8wa9MvKhAn3Va6MUaIl5f+V/AdXM0cYxymIklm3aOSLPyiAibvPYqLozS7gOfwTyjN3SH1XXq83SlpIT3mIhn1MtKYW3SKEEb8LVqVjb0FnngZgFfo9xXx4W/KLEK8F25Mjthu3lsPM5Uo/Vv7E6HDY72tMpjRLHep7hVbecIYlhXV/C0dfvrSnF0orWyKGBxAdODfAMEBvHPRxwqqUMrLujaybV1PguD3OC139ld9Ei56JPQA6klzUCUKeId1O8cNp1OfEiruqDhSQy9rNfibkGYSctBxZhZgNXSsR5VwVq5bjy5zFCggf0Pdp7wuw0Q0Lvc9SRFmMIFDazccaVriBkfvlgYXVO58ms5W6EQLWLVP9yM0lksaRK/j+z8wWF9PzGGkjUnai1ipGMGozxHw1S0XAs+b423Ws1rwuJ7uGI+nR9vQHrqg1832MErLP6k9PaqRaQYaZvDwUCfN+iT9e4vRwZvYe7ArZXJ8S3Q9W6I5tjaLmt3MueYuzbCfU7yjEHDeor2ulvLc+lhxb/MQzwfwhbOLrYg8LBaQjWdLGjn1ldhtoGXGahtnCatbWztpEUf3R6tq0mV1Ej/fux09GQe2fJKE0Ow5mcd+PupwoCSKB/dYMQLS5YqLyOuRjUhAeQBcQ5rpNV5TzpWE6mA1jDbuMhOv4eOBUvMTJlv1fHzx0Ztv+kPimQteKFxQDy4/YMFVaOWAnwuOHIk+oofqkeenHTz1PCsfXu/DJFnVGH333OgdGfT1sc+56e3E1RBQ/GfyHeE3gJzJ9ZYOjrdlT8D2Ec=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

