apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: k8s
spec:
  crossplane:
    version: ">=v1.5"
  dependsOn:
  - provider: crossplane/provider-aws
    version: ">=v0.20"
  - provider: crossplane/provider-gcp
    version: ">=v0.19"
  - provider: crossplane/provider-jet-azure
    version: ">=v0.4"
  - provider: crossplane/provider-helm
    version: ">=v0.9"
