apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: k8s
spec:
  crossplane:
    version: ">=v1.5"
  dependsOn:
  - provider: crossplane/provider-aws
    version: v0.20.1
  - provider: crossplane/provider-gcp
    version: v0.18.0
  - provider: crossplane/provider-jet-azure
    version: v0.4.0
  - provider: crossplane/provider-helm
    version: v0.5.0
