apiVersion: devopstoolkitseries.com/v1alpha1
kind: SgClaim
metadata:
  name: a-team
spec:
  id: a-team
  compositionSelector:
    matchLabels:
      provider: aws
      type: sg
  parameters:
    egressCidr: "0.0.0.0/0"
