apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeSQL
metadata:
  name: a-team-mysql
spec:
  id: a-team-mysql-2
  compositionRef:
    name: google-mysql
  parameters:
    version: "8_0"
    size: small
  writeConnectionSecretToRef:
    name: a-team-mysql
    namespace: a-team
