apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA6P0T6H80xwIIHcnw5e9yEcIZ3C3rqfqB93SV/s2YtYkdq+pHu9ELKOajfX4ltPdVTJBWQv7O1WAXUJkw0tNYHtKQF0f0Pjm46+WkciROFLWYZO1u/J3ndXOWY6inB3pVMBQTEPtn0jNgK5cJJT5V+WymfC7qPg5DLHkssdFY/0BI4nc3jCl7DQoc74wKmgM8Q+LvuaYpl2PQPRpGVlPnzOqoidXrySyOAbHy0TmuZ6YlFUe2zomKWWo6LRng5MDoGbB+n7HOOBuNEMNW1CuwOqn9UT3vFX1ZJAX6yTOmlh7/j/UTL/Xmg+HiTiJ0Yge4oE4kiZUQiyBcj5ZyoifRAqKC/OqVHEMGZA1LlRHm6us+kxHXrYhK+ppFxqvsNU0zY7ykoMyM3jgLx8Xo7kuaf/2PbLXsw90/TTI3r/0vf0JRllNSeOWB6s3r679t56RbiPj1La0rU8xc4S64X8Cx3C/RJynXHj7BK5GU4R6oAuMbOvSUcg0yrPqp8HJQNy6UxH2AIUqSo4rrXgh32ujtyb63KCfnAVNmeQsmY1K/S7XVY/EtY0zxJm3Vb6e10L6K8C3EgsCfTibWptNiI+WkM/bKeL2LjJhvihWIfg2KV93JaH5YmUv+pKfeBYhv/NSwS8u+PFJZjUS8OH7WP+SziVx1pCfWv5my0UXapLwQnQYYvMF6i/9Oq8r/JW3oOf68x8DO+GPD1cBG5eQeO36sV94ArhKSrfc2W6XYHFqfGhdzTGNHMCQpUjC3LJX2hb3qSkE+aPv83QvoAo8XLhhAv9Fdn54aGkB+RmzddP3B9uf7uMcnYploX6ik2pQoJ/AyrBI4sqga1XZPrwwcHJyZhHX5pMAo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

