apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAunjCCEOWjmw71V6T4bDhJMe9wxrAVR66BKw963ZqyA2G4jZa029Z/vkefDvnuxE6tvPrJxKF7LUcMGlyWEKWGmW4rgIf7Mpw4rB9AlPBNaVWcaFJ1eh4JB1QFoN1UBCW8ieDWeIbsSdVYZwbies/gICpDcRQuBwGz/b2Mj0SjcFmz0fl9xG6QtFUZlKvh81wMyxhuU3bIqaZ9PwWgJKNkJfx/J57O/vCStWuqHNrUDYuKWO1yOWJIh7rVOywBZiLg/+Eorf1aRabx9TjkSPsuFAazrOlweLnO5Ba7bBdSzM/HFIHNyk6De9o8w+EpLwfFB43NaSP9tpD7F4XJvUT6fR+9yZjxsXa2kXUwcsJZmAMHuwEap5wO/YN0mqSFXdOU0VCA5mtnVoj4kIyTIB/gSuBxQqJzPDIJlZE2Ov9PdIcvPKPxsszQBQQlc0RvPccwcAVj418Mp6eTI9kqTU94md2wWGQEUiYSnadd4rCxSDi1y+CkEibqNCkA0zm+Cqs+yWAbM78UnpulbNT8EOBrHK6ozBzorQkDSw3zWb67PjGor7q1zmiYH8OWhOZepVydhnY1pVwUwVSJBS3EeHTGyZESvsZz3WaJVRoAGFy24+u3g7sjW5Ph7qb3HTvAsAQY/oyOWhsB/BojKuNQw3Aomqh8xWv/c9YK7SAWmxSt9CeADKwQX8U7C/DvpYHVsRI4bB32iBCN2yAxPsA2SulKFkUu+9h3MJYhIOXsfFCoMs3nbV/WIHTJPl4OpG6o408PXV/hcSd4AXXM+oZ0Bf1XgP26yR9UKNYanSQK3ombCviA432j4kWTPa0G7fdbwI9tzP+BsECe7CffrcOA5q+cQ7k1T+Y=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

