apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgDHKtxHrAdhUkFZoEtR2u08DW3GkNFRq5hLajB9a7AeGkjAidEYOa/lfMzZEW6ZQ8bAvAMILYC2124j/BN8kq3EMQUyu2iXOpOqjIYk847vo0RR0xzIXkyrhv+o+Y4g4+1VcPXC7Sw8ILhUZqSleqDxBbRmsJ0qJgkPGr6fA3Oa7nTCIHV6o3/sTaN0O3jQS3Y1Dm2KsDcUl99KpaPR8R2HmrlYz30Na+WgAwStXY0axddnuO8VHmVfGihV3+VALFfPTjBE84Qq91D5CVwCkRJZ/5bWtbcJNtLnCBMQcElajrWyz+zkiupo6E+k8jz2Xi+xJAPKexbUVHjPxE4waXMsNoOi4DwfzagEPoX5oidY2FR3TsDt/y7uE6cEgd3dGe611cRh3UkuVspkNEukKFfQ9m5XvmF4UUWDuDLKS6XKdhLMFahVNm3ONz8DmgrQDse9Z0mrgq6lwFnQ/g7a+QtnzDf0deHixiku72HH6W9VDjBlv2NM4oCSv6IUyQWaW2dnM57mwrTgLwZpb0UDmeMm4b+ZlG5Kys6uPyzipGefVYAL7SdlByc7e09e/0iaZG/0jeyl2PaTN9F/2LICkJ/LZkY2k9UyGI1YZCwvqZBxIwUBN57oDMcEpwmAMeQLospYzn2lgauzU6puM7FWoIjnm7bmbbACDhrSiHsN5Tx05q0lw2j4TO5aLSMPEJMCQo0kHPgkzvKPyfhx6YkOIOn4mweK5tZoDeltoavHeEz9MSz00CemO2NfgAHeEJe99AeaDdrxsR4JpxykbSZAXwkSZ3LZIWDZLXdzHnJMpl+ICtNCdwkwISN3RMfaGB4Jh7EInMppVmvnpKXDPMB4BmRZWHJSYRI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

