apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAlsa9VTq92uYFh6TryOK3slUwGdNlMVm6G6JIULG9Q7HoGqR3ulM36Y4dl/Ay3nsvziu1c3iB58ZU96FjZDrdqkqhVTPOXtR9FbIco1U/8lC5lmwjhxVe5N7t2MvMqW8NZ35+yhl6tRtGA5BPl8Pmks3yFRo14FBPrNAsmcXOynps3U0cG2yDvgCk2RkfuSaXd+WTGuSwFIOluPEy2bIojNos8YPW9jm3VlcNiYwkTB1hBHVvZg7lmLyT2Bb+uG77rAcB3q6UKcNOD0XZokn71DSFn2gcQ+Xg5ADHVRcgFWPe4zPxdOu8RQNHB6YxPY1kBuSVbztIZyKKfMxYW4jEJdhK8H9US9INiyY+bguhol+fRkXXnZnNPysrxU2KiaNALpzKdAmEn5VirhdNkBpaQC3/Vo2qIC+JOEQ7Yu6ugo9JDA/36PdSncT9z9nlw1OGdz143DgRY/XTXktJdqjniTiJriArZlNNFxS6xqx696f/FRNvFBQKT4CnhBNInkD5DIv3hn80E4FKCs302ddruxjLwtTTHT12rFp1lDR/x2XO1tv5Px8S/nOSVtG6a1Tk2VYrBFd9VM/9Zs/4X3ZDNIuoZV4RgGo2wAbdgREoy1Cpaj5oR4AMUAWSLxipf/N255avVrBWaiT+7tfJB8tuMe6yvWkutS/oELlkp1Qb67U4gBpRsYeIRAp7bTLAkMo00OOudsf/lI9aE6aqwjhYNww9Kwl20kvZhzUg0pW2Zhq4hq+WchYBlPhdLRGOvCYPYdwoLFsPzR+w5jB5p+s2sOBF6RVpZ9Yqgm2c9cXhjmFg6URI43cIhXfUAkYrKjUxuxpPJ5I3wj4SDfyxljlVAfzLgZAM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

